version: "0.1"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    restart: always
    links:
      - "postgres:postgres"
  postgres:
    build: ./postgres
    ports:
      - "5432:5432"
    restart: always

